export const REQUEST_GET_USER = "REQUEST_GET_USER";
export const REQUEST_GET_USER_INIT = "REQUEST_GET_USER_INIT";
export const RECEIVE_GET_USER_SUCCESS = "RECEIVE_GET_USER_SUCCESS";
export const RECEIVE_GET_USER_ERROR = "RECEIVE_GET_USER_ERROR";
